name: unicode-general-category
version: 0.1.0.0
github: Javran/unicode-general-category
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2021 Javran Cheng"
synopsis: Unicode General Category Database
description:
  This package provides Unicode General Category data for Unicode 13.0.0.
  In addition it offers tools to process UnicodeData.txt content
  and turn it into a database compatible with this package.

category: Unicode

extra-source-files: embed/*

dependencies:
  - base >= 4.5 && <= 1000

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - array
    - bytestring
    - text
    - containers
    - file-embed
    - binary

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - unicode-general-category
      - QuickCheck
      - hspec
      - containers
      - bytestring
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
